/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capgemini.minhaprimeirainterfacegrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author gordo
 */
public class PrimeiraTela extends javax.swing.JFrame {

    /**
     * Creates new form PrimeiraTela
     */
    public PrimeiraTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TelaPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        SenhaTextField = new javax.swing.JTextField();
        DigiteLoginSenhaLabel = new javax.swing.JLabel();
        LogarButton = new javax.swing.JButton();
        EsqueciSenhaButton = new javax.swing.JButton();
        ErroLogarPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ErroLogarTextArea = new javax.swing.JTextArea();
        ErroLogarLabel = new javax.swing.JLabel();
        EnviarMsgButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Nomelabel = new javax.swing.JLabel();
        NomeText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaPanel.setBackground(new java.awt.Color(153, 255, 153));
        TelaPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginLabel.setText("Login");

        SenhaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SenhaLabel.setText("Senha");

        loginTextField.setForeground(new java.awt.Color(204, 204, 204));
        loginTextField.setText("<Digite seu login>");
        loginTextField.setToolTipText("Digite seu login");
        loginTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTextFieldMouseClicked(evt);
            }
        });

        SenhaTextField.setToolTipText("Digite sua senha");

        DigiteLoginSenhaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DigiteLoginSenhaLabel.setText("Digite seu login e senha para entrar no sistema:");

        LogarButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        LogarButton.setText("Logar");
        LogarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogarButtonMouseClicked(evt);
            }
        });

        EsqueciSenhaButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        EsqueciSenhaButton.setText("Esqueci minha senha");

        ErroLogarPanel.setBackground(new java.awt.Color(204, 204, 204));
        ErroLogarPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 51)));

        ErroLogarTextArea.setColumns(20);
        ErroLogarTextArea.setRows(5);
        jScrollPane1.setViewportView(ErroLogarTextArea);

        ErroLogarLabel.setText("Digite aqui seu erro ao tentar logar:");

        EnviarMsgButton.setText("Enviar mensagem");

        javax.swing.GroupLayout ErroLogarPanelLayout = new javax.swing.GroupLayout(ErroLogarPanel);
        ErroLogarPanel.setLayout(ErroLogarPanelLayout);
        ErroLogarPanelLayout.setHorizontalGroup(
            ErroLogarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErroLogarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ErroLogarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EnviarMsgButton)
                    .addGroup(ErroLogarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ErroLogarLabel)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ErroLogarPanelLayout.setVerticalGroup(
            ErroLogarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErroLogarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ErroLogarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnviarMsgButton)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout TelaPanelLayout = new javax.swing.GroupLayout(TelaPanel);
        TelaPanel.setLayout(TelaPanelLayout);
        TelaPanelLayout.setHorizontalGroup(
            TelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(TelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TelaPanelLayout.createSequentialGroup()
                            .addComponent(LoginLabel)
                            .addGap(18, 18, 18)
                            .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TelaPanelLayout.createSequentialGroup()
                            .addComponent(SenhaLabel)
                            .addGap(18, 18, 18)
                            .addComponent(SenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogarButton)
                            .addGap(32, 32, 32)
                            .addComponent(EsqueciSenhaButton)
                            .addGap(36, 36, 36)))
                    .addComponent(DigiteLoginSenhaLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ErroLogarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TelaPanelLayout.setVerticalGroup(
            TelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(DigiteLoginSenhaLabel)
                .addGap(18, 18, 18)
                .addGroup(TelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginLabel)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaLabel)
                    .addComponent(SenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogarButton)
                    .addComponent(EsqueciSenhaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErroLogarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Login", TelaPanel);

        Nomelabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Nomelabel.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Nomelabel)
                .addGap(30, 30, 30)
                .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nomelabel))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Criar Conta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogarButtonMouseClicked
        JOptionPane.showMessageDialog(rootPane,"Seja bem vindo!");
    }//GEN-LAST:event_LogarButtonMouseClicked

    private void loginTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTextFieldMouseClicked
     loginTextField.setText("");
    }//GEN-LAST:event_loginTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeiraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DigiteLoginSenhaLabel;
    private javax.swing.JButton EnviarMsgButton;
    private javax.swing.JLabel ErroLogarLabel;
    private javax.swing.JPanel ErroLogarPanel;
    private javax.swing.JTextArea ErroLogarTextArea;
    private javax.swing.JButton EsqueciSenhaButton;
    private javax.swing.JButton LogarButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTextField NomeText;
    private javax.swing.JLabel Nomelabel;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JTextField SenhaTextField;
    private javax.swing.JPanel TelaPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField loginTextField;
    // End of variables declaration//GEN-END:variables
}
